# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://morse-ws.github.io/'
baseurl: ''
title: 'International Workshop on Model-driven Robot Software Engineering'
description: 'International Workshop on Model-driven Robot Software Engineering'
permalink: pretty
logo: "https://raw.githubusercontent.com/morse-ws/morse-ws.github.io/master/images/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Morse 2020
  url: /pages/2020/
- title: People
  url: /pages/people/
- title: Past Editions
  url: /pages/editions/
- title: Contact
  url: /pages/contact/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
#collections:
#  posts:
#    title: Posts
#    output: true
#    description: "My thoughts and ideas"
#    feature_text: |
#      Welcome to my blog
#    feature_image: "https://picsum.photos/2560/600?image=866"
